before:
  hooks:
    - make clean
    - go mod download
    - go generate ./...
builds:
  - main: ./cmd/hetty
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    hooks:
      pre: make embed
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
